#!/usr/bin/env python3
"""Generate the manuscript reference-sequence comparison figure.

This script intentionally mirrors the current manuscript Figure 4 layout while
adding FID as a fourth sequence family.  It builds two representative protocol
realizations for each reference sequence and arranges them as a 4 x 2 figure:

    row 1: FID      baseline | protocol edit
    row 2: GRE      baseline | protocol edit
    row 3: EPI      baseline | protocol edit
    row 4: TSE      baseline | protocol edit

The immediate goal is to establish the *content and layout* of the combined
manuscript figure.  Publication typography is deliberately left to the shared
plotter; a later ``publication`` option can improve fonts, line widths, and
other rendering details without changing the figure-generation logic here.

Each cell is generated by the normal sequence demo implementation, resolved,
checked for timing, and rendered by ``Sequence.plot``.  The black command strip
records the protocol change represented by the panel, following the style of
the current manuscript figure as closely as practical.

Run from the ``examples`` directory or repository root:

    python examples/plot_reference_sequences.py

Outputs are written to ``out/reference_sequences`` by default.
"""

from __future__ import annotations

import argparse
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Callable

# Use a non-interactive backend unless the caller explicitly requests display.
if "--show" not in sys.argv:
    import matplotlib

    matplotlib.use("Agg")

import demo_EPI
import demo_FID
import demo_GRE
import demo_TSE
import matplotlib.pyplot as plt
from PIL import Image, ImageDraw, ImageFont

# =============================================================================
# DATA MODEL
# =============================================================================


@dataclass(frozen=True)
class PanelSpec:
    """Definition of one panel in the 4 x 2 manuscript figure."""

    label: str
    family: str
    title: str
    command_text: str
    builder: Callable[[], tuple[Any, tuple[str, ...]]]
    gradient_scale: str | None = None
    repetitions: int = 1
    one_tr: bool = False
    time_range: tuple[float, float] | None = None
    gradient_y_limit: float | None = None


@dataclass(frozen=True)
class PlotResult:
    """Result of building and rendering one panel."""

    spec: PanelSpec
    sequence: Any
    realization: Any
    timing_ok: bool
    timing_report: tuple[str, ...]
    png_path: Path
    summary_lines: tuple[str, ...]


# =============================================================================
# COMMON HELPERS
# =============================================================================


def _resolve_and_check(sequence: Any) -> tuple[Any, bool, tuple[str, ...]]:
    """Resolve one symbolic sequence and normalize its timing report."""

    realization = sequence.resolve()
    ok, report = realization.check_timing()
    return realization, bool(ok), tuple(str(item) for item in report)


def _save_sequence_plot(
    *,
    sequence: Any,
    realization: Any,
    output_path: Path,
    title: str,
    repetitions: int,
    dpi: int,
    width: float,
    height: float,
    gradient_scale: str | None,
    one_tr: bool,
    time_range: tuple[float, float] | None,
    gradient_y_limit: float | None,
    publication: bool,
    show: bool,
) -> None:
    """Render one panel using the normal PyPulseq-Star plotter."""

    plot_kwargs: dict[str, Any] = {
        "realization": realization,
        "repetitions": repetitions,
        "title": title,
        "one_tr": one_tr,
        "figsize": (width, height),
        "dpi": dpi,
        "debug": False,
        "show": show,
        "publication": publication,
    }
    if gradient_scale is not None:
        plot_kwargs["gradient_scale"] = gradient_scale
    if time_range is not None:
        plot_kwargs["time_range"] = time_range

    figure = sequence.plot(**plot_kwargs)
    if figure is None:
        figure = plt.gcf()

    # Use a common gradient scale when a side-by-side amplitude comparison is
    # part of the scientific message. Independent autoscaling can otherwise
    # make different amplitudes look deceptively similar.
    if gradient_y_limit is not None:
        for axis in figure.axes:
            ylabel = axis.get_ylabel().strip().lower()
            if ylabel.startswith(("gx", "gy", "gz")):
                axis.set_ylim(-gradient_y_limit, gradient_y_limit)

    figure.savefig(
        output_path,
        dpi=dpi,
        bbox_inches="tight",
        facecolor="white",
    )

    if show:
        plt.show()
    plt.close(figure)


def _font(size: int, *, bold: bool = False) -> ImageFont.ImageFont:
    """Return a portable font for panel labels and command strips."""

    candidates = (
        "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"
        if bold
        else "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
        "/Library/Fonts/Arial Bold.ttf" if bold else "/Library/Fonts/Arial.ttf",
        "C:/Windows/Fonts/arialbd.ttf" if bold else "C:/Windows/Fonts/arial.ttf",
    )

    for candidate in candidates:
        try:
            return ImageFont.truetype(candidate, size=size)
        except OSError:
            continue
    return ImageFont.load_default()


# =============================================================================
# PANEL BUILDERS
# =============================================================================


def _build_fid(*, num_samples: int, echo_time: float) -> tuple[Any, tuple[str, ...]]:
    """Build one FID realization."""

    overrides = {
        "average": 4,
        "num_samples": num_samples,
        "echo_time": echo_time,
        "repetition_time": 1.0,
    }
    system = demo_FID.define_system_limits()
    protocol = demo_FID.define_protocol(overrides=overrides)
    sequence, te_fill, tr_fill = demo_FID.build_sequence(system, protocol)

    notes = (
        f"num_samples={num_samples}",
        f"TE={echo_time * 1e3:.1f} ms",
        "TR=1000.0 ms",
        f"TE fill={te_fill.eval(sequence) * 1e3:.3f} ms",
        f"TR fill={tr_fill.eval(sequence) * 1e3:.3f} ms",
    )
    return sequence, notes


def _build_gre(*, n_y: int, fov_phase: float) -> tuple[Any, tuple[str, ...]]:
    """Build one scanner-safe GRE realization.

    Keep the scanner-tested read FOV unchanged and vary only the phase FOV.
    This preserves the intended protocol-edit demonstration without driving
    the readout gradient beyond the unchanged hardware limits.
    """

    overrides = {
        "n_y": n_y,
        "fov_phase": fov_phase,
        # Keep the current scanner-tested timing defaults.
        "echo_time": 6e-3,
        "repetition_time": 15e-3,
        "rf_spoiling_increment": 117.0,
    }
    system = demo_GRE.define_system_limits()
    protocol = demo_GRE.define_protocol(orientation="axial", overrides=overrides)
    sequence, te_fill, tr_fill = demo_GRE.build_sequence(
        system,
        protocol,
        orientation="axial",
    )

    notes = (
        "orientation=axial",
        f"n_y={n_y}",
        "FOV read=256.0 mm",
        f"FOV phase={fov_phase * 1e3:.1f} mm",
        "TE=6.0 ms",
        "TR=15.0 ms",
        f"TE fill={te_fill.eval(sequence) * 1e3:.3f} ms",
        f"TR fill={tr_fill.eval(sequence) * 1e3:.3f} ms",
    )
    return sequence, notes


def _build_epi(*, etl: int, fov_phase: float) -> tuple[Any, tuple[str, ...]]:
    """Build one segmented-EPI realization."""

    overrides = {
        "n_y": 64,
        "echo_train_length": etl,
        "fov_phase": fov_phase,
        # Retain current scanner-safe sequence defaults.
        "readout_duration": 640e-6,
        "echo_time": 30e-3,
        "repetition_time": 400e-3,
    }
    system = demo_EPI.define_system_limits()
    protocol = demo_EPI.define_protocol(orientation="axial", overrides=overrides)
    sequence = demo_EPI.build_sequence(system, protocol, orientation="axial")

    notes = (
        "orientation=axial",
        "n_y=64",
        f"ETL={etl}",
        f"FOV phase={fov_phase * 1e3:.1f} mm",
        "readout=640.0 us",
        "TE=30.0 ms",
        "TR=400.0 ms",
    )
    return sequence, notes


def _build_tse(
    *,
    etl: int,
    phase_order: str,
    orientation: str,
) -> tuple[Any, tuple[str, ...]]:
    """Build one TSE realization."""

    overrides = {
        "n_y": 128,
        "echo_train_length": etl,
        "phase_encode_order": phase_order,
        # Preserve the scanner-tested timing/RF defaults in the demo.
        "TE_effective": 64e-3,
        "repetition_time": 2.0,
        "refocusing_flip_angle": 180.0,
    }
    system = demo_TSE.define_system_limits()
    protocol = demo_TSE.define_protocol(
        orientation=orientation,
        overrides=overrides,
    )
    sequence, first_refocus_fill, pre_readout_fill, tr_fill = demo_TSE.build_sequence(
        system,
        protocol,
        orientation=orientation,
    )

    notes = (
        f"orientation={orientation}",
        "n_y=128",
        f"ETL={etl}",
        f"order={phase_order}",
        "effective TE=64.0 ms",
        "TR=2000.0 ms",
        f"first-refocus fill={first_refocus_fill.eval(sequence) * 1e3:.3f} ms",
        f"pre-readout fill={pre_readout_fill.eval(sequence) * 1e3:.3f} ms",
        f"TR fill={tr_fill.eval(sequence) * 1e3:.3f} ms",
    )
    return sequence, notes


def _panel_specs() -> tuple[PanelSpec, ...]:
    """Return the eight fixed manuscript comparison panels.

    The GRE/EPI/TSE command strings intentionally stay close to those in the
    existing Figure 4.  Sequence-internal scanner-safety changes remain in the
    demo implementations and are therefore not repeated in the labels.
    """

    return (
        # ------------------------------------------------------------------
        # Row 1: FID -- new row for the revised combined figure.
        # ------------------------------------------------------------------
        PanelSpec(
            label="a)",
            family="FID",
            title="PyPulseq-Star FID",
            command_text="./demo_FID.py  --num-samples 1024  --te 0.020",
            builder=lambda: _build_fid(num_samples=1024, echo_time=20e-3),
            one_tr=False,
            time_range=(0.0, 0.080),
        ),
        PanelSpec(
            label="b)",
            family="FID",
            title="PyPulseq-Star FID",
            command_text="./demo_FID.py  --num-samples 2048  --te 0.030",
            builder=lambda: _build_fid(num_samples=2048, echo_time=30e-3),
            one_tr=False,
            time_range=(0.0, 0.080),
        ),
        # ------------------------------------------------------------------
        # Row 2: GRE -- mirrors current Figure 4 as closely as possible.
        # ------------------------------------------------------------------
        PanelSpec(
            label="c)",
            family="Spoiled GRE",
            title="PyPulseq-Star Spoiled GRE (axial)",
            command_text="./demo_GRE.py  --n-y 64  --fov-phase 0.128",
            builder=lambda: _build_gre(n_y=64, fov_phase=0.128),
            one_tr=False,
            gradient_scale="mt_per_m",
            time_range=(0.0, 0.015),
            gradient_y_limit=30.0,
        ),
        PanelSpec(
            label="d)",
            family="Spoiled GRE",
            title="PyPulseq-Star Spoiled GRE (axial)",
            command_text="./demo_GRE.py  --n-y 128  --fov-phase 0.064",
            builder=lambda: _build_gre(n_y=128, fov_phase=0.064),
            one_tr=False,
            gradient_scale="mt_per_m",
            time_range=(0.0, 0.015),
            gradient_y_limit=30.0,
        ),
        # ------------------------------------------------------------------
        # Row 3: EPI -- mirrors current Figure 4.
        # ------------------------------------------------------------------
        PanelSpec(
            label="e)",
            family="Segmented EPI",
            title="PyPulseq-Star Segmented EPI (axial)",
            command_text="./demo_EPI.py  --etl 8  --fov-phase 0.22",
            builder=lambda: _build_epi(etl=8, fov_phase=0.22),
            one_tr=False,
            gradient_scale="mt_per_m",
            time_range=(0.0, 0.025),
        ),
        PanelSpec(
            label="f)",
            family="Segmented EPI",
            title="PyPulseq-Star Segmented EPI (axial)",
            command_text="./demo_EPI.py  --etl 16  --fov-phase 0.18",
            builder=lambda: _build_epi(etl=16, fov_phase=0.18),
            one_tr=False,
            gradient_scale="mt_per_m",
            time_range=(0.0, 0.025),
        ),
        # ------------------------------------------------------------------
        # Row 4: TSE -- mirrors current Figure 4.
        # ------------------------------------------------------------------
        PanelSpec(
            label="g)",
            family="TSE",
            title="PyPulseq-Star TSE (axial)",
            command_text=(
                "./demo_TSE.py  --etl 8  --phase-order linear  "
                "--orientation axial"
            ),
            builder=lambda: _build_tse(
                etl=8,
                phase_order="linear",
                orientation="axial",
            ),
            one_tr=False,
            gradient_scale="mt_per_m",
            time_range=(0.0, 0.300),
        ),
        PanelSpec(
            label="h)",
            family="TSE",
            title="PyPulseq-Star TSE (sagittal)",
            command_text=(
                "./demo_TSE.py  --etl 16  --phase-order centric  "
                "--orientation sagittal"
            ),
            builder=lambda: _build_tse(
                etl=16,
                phase_order="centric",
                orientation="sagittal",
            ),
            one_tr=False,
            gradient_scale="mt_per_m",
            time_range=(0.0, 0.300),
        ),
    )


# =============================================================================
# 4 x 2 MANUSCRIPT COMPOSITE
# =============================================================================


def _fit_text_font(
    draw: ImageDraw.ImageDraw,
    text: str,
    *,
    max_width: int,
    initial_size: int,
    minimum_size: int = 16,
) -> ImageFont.ImageFont:
    """Choose the largest font that keeps one line inside ``max_width``."""

    for size in range(initial_size, minimum_size - 1, -1):
        font = _font(size)
        box = draw.textbbox((0, 0), text, font=font)
        if box[2] - box[0] <= max_width:
            return font
    return _font(minimum_size)


def _make_composite(
    results: list[PlotResult],
    output_path: Path,
    *,
    dpi: int = 300,
    column_gap: int = 22,
    row_gap: int = 16,
    outer_margin: int = 22,
) -> None:
    """Arrange eight plots in the Figure-4-like 4 x 2 layout."""

    if len(results) != 8:
        raise ValueError("The manuscript composite requires exactly eight panels.")

    loaded = [Image.open(result.png_path).convert("RGB") for result in results]

    # Equalize cell sizes without distorting the underlying timing plots.
    target_width = max(image.width for image in loaded)
    target_height = max(image.height for image in loaded)

    normalized: list[Image.Image] = []
    for image in loaded:
        scale = min(target_width / image.width, target_height / image.height)
        resized = image.resize(
            (round(image.width * scale), round(image.height * scale)),
            Image.Resampling.LANCZOS,
        )
        panel = Image.new("RGB", (target_width, target_height), "white")
        panel.paste(
            resized,
            (
                (target_width - resized.width) // 2,
                (target_height - resized.height) // 2,
            ),
        )
        normalized.append(panel)

    canvas_width = outer_margin * 2 + target_width * 2 + column_gap
    canvas_height = outer_margin * 2 + target_height * 4 + row_gap * 3
    canvas = Image.new("RGB", (canvas_width, canvas_height), "white")

    # First place the eight timing plots.
    panel_positions: list[tuple[int, int]] = []
    for index, panel in enumerate(normalized):
        row, col = divmod(index, 2)
        x = outer_margin + col * (target_width + column_gap)
        y = outer_margin + row * (target_height + row_gap)
        canvas.paste(panel, (x, y))
        panel_positions.append((x, y))

    # Then overlay Figure-4-style panel letters and black command banners.
    draw = ImageDraw.Draw(canvas)
    label_font = _font(max(26, round(target_width * 0.050)), bold=True)

    for result, (x, y) in zip(results, panel_positions):
        spec = result.spec

        # Panel label in the upper-left portion of each cell.
        draw.text(
            (x + round(target_width * 0.018), y + round(target_height * 0.060)),
            spec.label,
            font=label_font,
            fill="black",
        )

        # Command strip: deliberately similar to the current manuscript figure.
        banner_left = x + round(target_width * 0.33)
        banner_right = x + target_width - round(target_width * 0.025)
        banner_top = y + round(target_height * 0.075)
        banner_height = max(34, round(target_height * 0.100))
        banner_bottom = banner_top + banner_height

        draw.rectangle(
            (banner_left, banner_top, banner_right, banner_bottom),
            fill=(24, 24, 24),
        )

        horizontal_padding = max(10, round(target_width * 0.012))
        available_width = banner_right - banner_left - 2 * horizontal_padding
        command_font = _fit_text_font(
            draw,
            spec.command_text,
            max_width=available_width,
            initial_size=max(16, round(target_width * 0.026)),
            minimum_size=12,
        )
        text_box = draw.textbbox((0, 0), spec.command_text, font=command_font)
        text_height = text_box[3] - text_box[1]
        text_y = banner_top + (banner_height - text_height) // 2 - text_box[1]
        draw.text(
            (banner_left + horizontal_padding, text_y),
            spec.command_text,
            font=command_font,
            fill="white",
        )

    canvas.save(output_path, dpi=(dpi, dpi))


def _write_summary(results: list[PlotResult], path: Path) -> None:
    """Write the exact panel definitions and timing-check results."""

    lines = [
        "PyPulseq-Star reference-sequence manuscript comparison",
        "=" * 62,
        "",
    ]

    for result in results:
        lines.append(
            f"{result.spec.label} {result.spec.family}: "
            f"{'PASS' if result.timing_ok else 'FAIL'}"
        )
        lines.append(f"  command label: {result.spec.command_text}")
        for note in result.summary_lines:
            lines.append(f"  {note}")
        if result.timing_report:
            lines.append("  timing report:")
            lines.extend(f"    - {item}" for item in result.timing_report)
        lines.append(f"  figure: {result.png_path}")
        lines.append("")

    path.write_text("\n".join(lines), encoding="utf-8")


# =============================================================================
# CLI / MAIN
# =============================================================================


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Build the eight reference-sequence manuscript panels and combine "
            "them into a Figure-4-like 4 x 2 layout."
        )
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("out/reference_sequences"),
        help="Directory for panel PNGs, composite PNG, and run summary.",
    )
    parser.add_argument("--dpi", type=int, default=300)
    parser.add_argument("--composite-dpi", type=int, default=300)
    parser.add_argument("--panel-width", type=float, default=12.0)
    parser.add_argument("--panel-height", type=float, default=6.8)
    parser.add_argument(
        "--show",
        action="store_true",
        help="Display individual figures interactively in addition to saving them.",
    )
    parser.add_argument(
        "--no-publication",
        action="store_true",
        help="Disable publication-mode typography for A/B comparison.",
    )
    parser.add_argument(
        "--no-composite",
        action="store_true",
        help="Generate the eight individual panels only.",
    )
    parser.add_argument(
        "--continue-on-failure",
        action="store_true",
        help="Generate all panels even if one timing check fails.",
    )
    return parser


def main() -> int:
    args = _parser().parse_args()
    output_dir: Path = args.output_dir
    output_dir.mkdir(parents=True, exist_ok=True)

    results: list[PlotResult] = []
    failures: list[str] = []

    for spec in _panel_specs():
        slug = spec.family.lower().replace(" ", "_").replace("-", "_")
        panel_slug = spec.label.rstrip(")")
        png_path = output_dir / f"{panel_slug}_{slug}_timing.png"

        print(f"\n{'=' * 76}")
        print(f"Building panel {spec.label} {spec.family}")
        print(spec.command_text)
        print("=" * 76)

        try:
            sequence, notes = spec.builder()
            realization, timing_ok, timing_report = _resolve_and_check(sequence)

            print(f"Timing check: {'PASS' if timing_ok else 'FAIL'}")
            for item in timing_report:
                print(f"  {item}")

            _save_sequence_plot(
                sequence=sequence,
                realization=realization,
                output_path=png_path,
                title=spec.title,
                repetitions=spec.repetitions,
                dpi=args.dpi,
                width=args.panel_width,
                height=args.panel_height,
                gradient_scale=spec.gradient_scale,
                one_tr=spec.one_tr,
                time_range=spec.time_range,
                gradient_y_limit=spec.gradient_y_limit,
                publication=not args.no_publication,
                show=args.show,
            )
            print(f"Wrote timing diagram: {png_path}")

            results.append(
                PlotResult(
                    spec=spec,
                    sequence=sequence,
                    realization=realization,
                    timing_ok=timing_ok,
                    timing_report=timing_report,
                    png_path=png_path,
                    summary_lines=notes,
                )
            )

            if not timing_ok:
                failures.append(f"{spec.label} {spec.family}")

        except Exception as exc:
            failures.append(f"{spec.label} {spec.family}: {exc}")
            print(f"Panel generation failed: {exc}")
            if not args.continue_on_failure:
                raise

    summary_path = output_dir / "reference_sequence_summary.txt"
    _write_summary(results, summary_path)
    print(f"\nWrote run summary: {summary_path}")

    if not args.no_composite:
        if len(results) == 8:
            composite_path = output_dir / "reference_sequence_capabilities.png"
            _make_composite(
                results,
                composite_path,
                dpi=args.composite_dpi,
            )
            print(f"Wrote 4 x 2 composite: {composite_path}")
        else:
            print("Composite skipped because not all eight panels were generated.")

    if failures:
        print("\nPanel/timing failures:")
        for failure in failures:
            print(f"  - {failure}")
        if not args.continue_on_failure:
            return 1

    print("\nAll requested reference-sequence panels were generated.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
